### ISSUE TITLE
Instagram Legacy API Deprecated

### ISSUE THREAD

**Issue by paavo** [code-q-web-factory/neos-instagram#2]
> The remaining Instagram Legacy API permission ("Basic Permission") was disabled on June 29, 2020. As of June 29, third-party apps no longer have access to the Legacy API. 
https://www.instagram.com/developer/

Looks like we need to switch to [Instagram oEmbed](https://developers.facebook.com/docs/instagram/oembed) (Facebook API) to make this work again.

**Comment by rolandschuetz** [comment]
Yes. I'm currently not using this package. But I would be happy to help you.

**Comment by rolandschuetz** [comment]
Done: https://github.com/code-q-web-factory/neos-instagram/releases/tag/v2.0.0
